
export const answerActionTypes = {
	SAVE_ANSWER_INITIATED: 'SAVE_ANSWER_INITIATED',
	SAVE_ANSWER_SUCCESS: 'SAVE_ANSWER_SUCCESS',
	SAVE_ANSWER_FAILED: 'SAVE_ANSWER_FAILED'
};

export const questionsActionTypes = {
	FETCH_QUESTIONS_INITIATED: 'FETCH_QUESTIONS_INITIATED',
	FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
	FETCH_QUESTIONS_FAILED: 'FETCH_QUESTIONS_FAILED',
	SELECT_QUESTION: 'SELECT_QUESTION',
	SAVE_QUESTION_INITIATED: 'SAVE_QUESTION_INITIATED',
	SAVE_QUESTION_SUCCESS: 'SAVE_QUESTION_SUCCESS',
	SAVE_QUESTION_FAILED: 'SAVE_QUESTION_FAILED'
};

export const userActionTypes = {
	FETCH_USERS_INITIATED: 'FETCH_USERS_INITIATED',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	FETCH_USERS_FAILED: 'FETCH_USERS_FAILED',
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT'
};

